### ISSUE TITLE
using definitions as document toplevel properties throws error

### ISSUE THREAD

**Issue by dashameter** [dashevo/js-dpp#185]
Creating a document using JSON:

```
{
    "note": {
        "$ref": "#/definitions/msg"
    },
    "definitions": {
        "msg": {
            "required": [
                "timestamp"
            ],
            "properties": {
                "timestamp": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        }
    }
}
```

and setting definitions via

```
        const definitions = json.definitions;
        delete json.definitions;
        const contract = await platform.contracts.create(json, identity);
        contract.setDefinitions(definitions);
        await platform.dpp.dataContract.validate(contract);
```

`dpp.dataContract.validate(contract)` throws

```

TypeError: Cannot set property '$id' of undefined
    at enrichDataContractWithBaseSchema.js:43
    at Array.forEach (<anonymous>)
    at enrichDataContractWithBaseSchema.js:42
    at Array.forEach (<anonymous>)
    at i (enrichDataContractWithBaseSchema.js:28)
    at c.g [as validateDataContract] (validateDataContractFactory.js:59)
```
`contract.JSON()` as output by browser debug console (since `node` version is broken):

```
contract: DataContract
definitions:
msg:
additionalProperties: false
properties:
description: {type: "string"}
timestamp: {type: "number"}
required: Array(1)
0: "timestamp"
length: 1
documents:
note:
$ref: "#/definitions/msg"
entropy: "yd8ob63kZQ2c2aKsBgAcsik9SvC6xpLzoZ"
id: "2DEBGqaZDhxA8JSmdvsGUzucW7GLUzDtJKRzkN3teJZy"
ownerId: "32EfBxtPmTDSmdohuRFJ6EUTm92WPgyVojFrxyW9rKbi"
schema: "https://schema.dash.org/dpp-0-4-0/meta/data-contract"
```

**Comment by thephez** [comment]
@dashameter The issue with definitions only occurs when they are included in a document and then deleted out? Or definitions fail for you regardless of how you try to use them?

**Comment by shumkov** [comment]
@dashameter You define "definitions" as a document. You need "definitions" sections, not "documents".

**Comment by dashameter** [comment]
Using `$ref` directly at the toplevel:
```
        note: {
              $ref: '#/definitions/msg'
        }
```
example script:

```

const Dash = require('dash')

const clientOpts = {
  network: 'testnet',
    wallet: {
        mnemonic: ''
    }
}
const client = new Dash.Client(clientOpts)

const registerContract = async function() {
  try {
    const platform = client.platform
    const identity = await platform.identities.get('')

    const contractDocumentWithDefinitions = {
      documents: {
        note: {
              $ref: '#/definitions/msg'
        }
      },
      definitions: {
        msg: {
          required: ['timestamp'],
          properties: {
            timestamp: {
              type: 'number'
            },
            description: {
              type: 'string'
            }
          },
          additionalProperties: false
        }
      }
    }
    const { documents, definitions } = contractDocumentWithDefinitions

    const contract = await platform.contracts.create(documents, identity)
    console.dir({ contract })

    // Set contract definitions
    contract.setDefinitions(definitions)
    console.dir({ contract })

    // Make sure contract passes validation checks
    await platform.dpp.dataContract.validate(contract)

    // Sign and submit the data contract
    await platform.contracts.broadcast(contract, identity)
  } catch (e) {
    console.error('Something went wrong:', e)
  } finally {
    client.disconnect()
  }
}

registerContract()
```

throws the error:

```
{ contract:
   DataContract {
     id: '13ygEjg1q2iQHuZtyBgtAW9Wmyiufy9j9XVyPWkqKiJF',
     ownerId: '5aAinbP9UKXdWTyywW9C7Qk6u8WbkKDg4gNzYZbhTqfr',
     schema: 'https://schema.dash.org/dpp-0-4-0/meta/data-contract',
     documents: { note: { '$ref': '#/definitions/msg' } },
     definitions:
      { msg:
         { required: [ 'timestamp' ],
           properties:
            { timestamp: { type: 'number' },
              description: { type: 'string' } },
           additionalProperties: false } },
     entropy: 'yaWRRS8j6pQSqaTFSdDcM5i5q6XXJjYRFQ' } }

     
Something went wrong: TypeError: Cannot set property '$id' of undefined
    at Object.keys.forEach (node_modules/@dashevo/dpp/lib/dataContract/enrichDataContractWithBaseSchema.js:42:41)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach (node_modules/@dashevo/dpp/lib/dataContract/enrichDataContractWithBaseSchema.js:41:8)
    at Array.forEach (<anonymous>)
    at enrichDataContractWithBaseSchema (node_modules/@dashevo/dpp/lib/dataContract/enrichDataContractWithBaseSchema.js:28:32)
    at DataContractFacade.validateDataContract (node_modules/@dashevo/dpp/lib/dataContract/validateDataContractFactory.js:59:34)
```

**Comment by thephez** [comment]
Try this:
```      
      documents: {
        note: {
          properties: {
            $ref: '#/definitions/msg'
          }
        }
      },
```

**Comment by shumkov** [comment]
It supposed to work. We will fix it, thank you. Atm, you can try the @thephez’s workaround.
